# Set var "WDIR" to workdir
<% if @args[0] %>
<% WDIR=@args[0] %> 
<% else %>
<% WDIR=ENV["PWD"] %>
<% end %>

name: <%= WDIR.split('/').last  %>
root: <%= @args[0] %>

startup_window: talker
windows:
  - dev:
      layout: even-vertical
      # panes:
        # - ros2 run demo_nodes_cpp talker
  # - main:
  #     layout: even-vertical
      # panes:
        # - ros2 run demo_nodes_cpp listener