version: "3.8"
services:
  ros2:
    build:
      context: .
      args:
        - WORKSPACE=${WORKSPACE:-dev_ws}
        - EXPERIMENTAL_ZENOH_RMW=TRUE
    image: ${IMAGE_NAME:-ros2-humble-dev}:${IMAGE_TAG:-latest}
    container_name: ros2-humble
    privileged: true
    network_mode: host
    runtime: nvidia
    # Add these lines for terminal support
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
      # Add TERM environment variable
      - TERM=xterm-256color
    volumes:
      - ${HOME}/${WORKSPACE:-dev_ws}:/home/docker/${WORKSPACE:-dev_ws}:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/docker/.Xauthority:ro
      # Fix the session.yml path to match the docker user's home
      - ./.session.yml:/home/docker/.session.yml
      - ./.tmux.conf:/home/docker/.tmux.conf
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # Fix the command to use the correct path
    command: ["tmuxinator", "start", "-p", "/home/docker/.session.yml"]
  ros2-dockerhub:
    image: ahamboeck1/spotros2
    container_name: ros2-humble-local
    privileged: true
    network_mode: host
    runtime: nvidia
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
    volumes:
      - ${HOME}/${WORKSPACE:-dev_ws}:/root/${WORKSPACE:-dev_ws}:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./.session.yml:/root/.session.yml
      - ./.tmux.conf:/root/.tmux.conf
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command: ["tmuxinator", "start", "-p", "/root/.session.yml"]