version: "3.8"
services:
  ros2:
    build:
      context: .
      args:
        - WORKSPACE=${WORKSPACE:-dev_ws}
    image: ${IMAGE_NAME:-ros2-humble-dev}:${IMAGE_TAG:-latest}
    privileged: true
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
    volumes:
      - ${HOME}/${WORKSPACE:-dev_ws}:/root/${WORKSPACE:-dev_ws}:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./utilities:/utilities:rw
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      if [ -f /root/${WORKSPACE:-dev_ws}/install/local_setup.bash ]; then
        source /root/${WORKSPACE:-dev_ws}/install/local_setup.bash
      fi &&
      tail -f /dev/null
      "